# Generated by Django 5.1.4 on 2024-12-05 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Марка")),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Страна"
                    ),
                ),
            ],
            options={
                "verbose_name": "Марка",
                "verbose_name_plural": "Марки",
            },
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Модель")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="cars.carbrand",
                        verbose_name="Марка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модель",
                "verbose_name_plural": "Модели",
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "vin",
                    models.CharField(max_length=17, unique=True, verbose_name="VIN-номер"),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Год выпуска")),
                ("mileage", models.PositiveIntegerField(verbose_name="Пробег")),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость покупки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("for_sale", "В продаже"),
                            ("in_progress", "В работе"),
                            ("sold", "Продан"),
                        ],
                        default="for_sale",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("purchase_date", models.DateField(verbose_name="Дата покупки")),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена продажи",
                    ),
                ),
                (
                    "sale_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата продажи"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cars.carbrand",
                        verbose_name="Марка",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cars.carmodel",
                        verbose_name="Модель",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автомобиль",
                "verbose_name_plural": "Автомобили",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("repaid", "Ремонт"),
                            ("documents", "Документы"),
                            ("delivery", "Доставка"),
                            ("other", "Прочее"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Тип расхода",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма расхода"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата расхода")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="cars.vehicle",
                        verbose_name="Автомобиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расход",
                "verbose_name_plural": "Расходы",
            },
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(max_length=100, verbose_name="Имя покупателя"),
                ),
                (
                    "buyer_contact",
                    models.CharField(
                        max_length=100, verbose_name="Контактные данные покупателя"
                    ),
                ),
                (
                    "deal_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена сделки"
                    ),
                ),
                ("deal_date", models.DateField(verbose_name="Дата сделки")),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Прибыль"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal",
                        to="cars.vehicle",
                        verbose_name="Автомобиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сделка",
                "verbose_name_plural": "Сделки",
            },
        ),
    ]
