# Generated by Django 5.1.4 on 2024-12-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="buyer_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="Информация о покупателе"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="seller_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="Информация о продавце"
            ),
        ),
        migrations.DeleteModel(
            name="Deal",
        ),
    ]
