# Generated by Django 5.1.4 on 2024-12-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_vehicle_buyer_info_vehicle_seller_info_delete_deal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="purchase_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата покупки"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Стоимость покупки",
            ),
        ),
    ]
