# Generated by Django 5.1.4 on 2024-12-07 07:31

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.user_photo_path
            ),
        ),
    ]
